Deployment environments

diff --git a/bin/deploy-immediately b/bin/deploy-immediately
--- a/bin/deploy-immediately
+++ b/bin/deploy-immediately
@@ -1,3 +1,10 @@
 #!/bin/bash
 
-node --enable-source-maps bin/upload
+die () {
+    echo >&2 "$@"
+    exit 1
+}
+
+[ "$#" -eq 1 ] || die "1 argument required, $# provided"
+
+node --enable-source-maps bin/upload --env "${@: -1}"
